name: PR Greeting

# Trigger the workflow only when a pull request is opened
on:
  pull_request:
    types:
      - opened

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output greeting based on PR
        run: |
          if [ "${{ github.event.pull_request.user.login }}" == "team" ]; then
            echo "Hello Quality Team"
          else
            echo "Hello Quality Experts"
          fi
