name: Hello Quality Team or Experts

on:
  workflow_dispatch:
    inputs:
      greeting_option:
        description: 'Choose the greeting message'
        required: true
        default: 'team'
        type: choice
        options:
          - team
          - experts

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output greeting
        run: |
          if [ "${{ github.event.inputs.greeting_option }}" == "team" ]; then
            echo "Hello Quality Team"
          else
            echo "Hello Quality Experts"
          fi
